### ISSUE TITLE
Error - bash: line 10

### ISSUE THREAD

**Issue by iamenderst** [kosmonavtika/pve-patch#1]
Fresh install before and after latest updates I get:
`# wget -qO - https://raw.githubusercontent.com/kosmonavtika/pve-patch/master/patch.sh | bash
- patch pve-manager/6.0-4/2a719255 (running kernel: 5.0.15-1-pve)...
- download and copy files...
cp: cannot stat '/usr/share/pve-patch/scripts/90pvepatch': No such file or directory
bash: line 10: /usr/share/pve-patch/scripts/apply.sh: No such file or directory
- done!
`

**Comment by kosmonavtika** [comment]
Thanks noticing! Fixed with commit 9829d4a64be95bdb1e9deac7f5e5c8d45876a5c1. :-)
