### ISSUE TITLE
Update for latest version(s) of Proxmox VE

### ISSUE THREAD

**Issue by kosmonavtika** [kosmonavtika/pve-patch#3]
Hey,

This patch could use an update to support the latest version of Proxmox VE. If you feel like contributing, please submit a PR. The modifications required shouldn't to be too bad.  I'd do it myself, but I'm not using Proxmox VE at the moment. :)

**Comment by myrandor** [comment]
I just run the script on ProxMox 6.2-12 on Debian Buster. Seems to run fine!

Only issue is the new image, is a bit too big (it's trimmed).

Also, why not use the original Proxmox logos?

<img width="348" alt="Screen capture" src="https://user-images.githubusercontent.com/1619223/101289917-60653180-37cd-11eb-96bd-f3768bd84659.png">

**Comment by Onepamopa** [comment]
Does it work on 6.3-2 ?

**Comment by myrandor** [comment]
I didn't update any of my 2 Proxmox server to 6.3+ yet. I use a patch to make incremental backup and it's not updated to 6.3 yet.

**Comment by Onepamopa** [comment]
Fix for latest version @ apply.sh:
sed -i.bak "s/data.status.toLowerCase() !== 'active'/false/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js

**Comment by kosmonavtika** [comment]
> I just run the script on ProxMox 6.2-12 on Debian Buster. Seems to run fine!
> 
> Only issue is the new image, is a bit too big (it's trimmed).
> 
> Also, why not use the original Proxmox logos?
> 
> <img alt="Screen capture" width="348" src="https://user-images.githubusercontent.com/1619223/101289917-60653180-37cd-11eb-96bd-f3768bd84659.png">

I was testing theming on Proxmox and decided I would replace the logos as well. I stopped using Proxmox before I could finish it, though. Feel free to submit a PR that makes changing the branding optional. :)

**Comment by kosmonavtika** [comment]
> Fix for latest version @ apply.sh:
> sed -i.bak "s/data.status.toLowerCase() !== 'active'/false/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js

Great! Thanks! Would you mind submitting the change as a pull request? :)

**Comment by myrandor** [comment]
Sorry for the delay. Pull request done. I've removed the "images" replacement and put some adjustments in the patching process.
#4

**Comment by kosmonavtika** [comment]
Thanks! I've merged your changes. :)
