### ISSUE TITLE
Update for Proxmox 6.3-4

### ISSUE THREAD

**Issue by GJKrupa** [kosmonavtika/pve-patch#5]
Looks like they've split the code over two lines as well as changing it to lowercase
```
                    if (res === null || res === undefined || !res || res
                        .data.status.toLowerCase() !== 'active') {
```

Maybe something like...
```
sed -i.bak -z "s/if ([^{]*data.status[^ ]* !== 'active'[^{]*) {/if (false) {/gi" $JSLIBFILE
```
which will be able to handle pretty much any single- or multi-line condition (I'm specifically checking for not '{' instead of not ')' so it won't break if they add more function calls into the condition.

If I run this and do a diff on the result I'm seeing the following which looks to be as expected on the new version:
```
457,458c457
< 		    if (res === null || res === undefined || !res || res
< 			.data.status.toLowerCase() !== 'active') {
---
> 		    if (false) {
```

Alternatively:
```
sed -i.bak "s/checked_command:/checked_command: function(orig_cmd) { orig_cmd(); }, xyzzy:/" $JSLIBFILE
```
will just nullify the checking function altogether and rename the old one to xyzzy or whatever meaningless name you want to apply but it's not idempotent (though you're using grep to check if the change is already applied anyway).

**Comment by mikedamm** [comment]
@kosmonavtika would you mind merging this?

**Comment by kosmonavtika** [comment]
Sorry for my inactivity. I merged the PR of @whattheserver, which includes support for Proxmox 6.3-4 and more. Thanks everyone.
